config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  excludes: ''

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  UnusedPrivateProperty:
    active: false
