name: Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Build APK and Bundle
        run: ./gradlew assembleDebug bundleDebug

      - name: Upload APK and Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/bundle/debug/*.aab