name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run UI Tests
        run: ./gradlew connectedCheck

      - name: Setup Detekt
        run: curl -sSLO https://github.com/detekt/detekt/releases/download/v1.18.1/detekt-cli-1.18.1-all.jar

      - name: Run Detekt
        run: java -jar detekt-cli-1.18.1-all.jar --input src --config detekt-config.yml

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: |
            app/build/reports
            app/build/outputs
